# Generated by Django 4.0 on 2023-05-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='thread',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='thread',
            name='first_person',
            field=models.TextField(blank=True, default=None, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='thread',
            name='second_person',
            field=models.TextField(blank=True, default=None, max_length=10000, null=True),
        ),
    ]
