# Generated by Django 4.0 on 2023-05-26 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_thread_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='user',
            field=models.TextField(blank=True, default=None, max_length=10000, null=True),
        ),
    ]
