# Generated by Django 4.1.6 on 2023-04-24 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile_finder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField()),
                ('mobile', models.IntegerField()),
                ('password', models.TextField()),
                ('confirm_password', models.TextField()),
                ('referral_code', models.CharField(blank=True, default=None, max_length=6, null=True)),
                ('code', models.CharField(blank=True, default=None, max_length=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='profile_finder_new',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField()),
                ('mobile', models.IntegerField()),
                ('password', models.TextField()),
                ('confirm_password', models.TextField()),
                ('referral_code', models.CharField(blank=True, default=None, max_length=6, null=True)),
                ('code', models.CharField(blank=True, default=None, max_length=6, null=True)),
            ],
        ),
    ]
