# Generated by Django 4.1.6 on 2023-04-24 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_finder', '0002_profile_finder_user_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_finder',
            name='idcard',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='pictures'),
        ),
    ]
