# Generated by Django 4.1.6 on 2023-04-27 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_finder', '0008_profile_finder_address_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_finder',
            name='upload_id',
            field=models.FileField(blank=True, default=None, max_length=500, null=True, upload_to='profileid'),
        ),
    ]
