# Generated by Django 4.1.6 on 2023-04-27 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_finder', '0009_profile_finder_upload_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile_finder',
            old_name='upload_id',
            new_name='upload_idcard',
        ),
    ]
