# Generated by Django 4.1.6 on 2023-04-29 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_finder', '0010_rename_upload_id_profile_finder_upload_idcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_finder',
            name='profile_picture',
            field=models.FileField(blank=True, default=None, max_length=500, null=True, upload_to='profilepicture'),
        ),
    ]
