# Generated by Django 4.1.6 on 2023-05-01 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_finder', '0011_profile_finder_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countryCode', models.TextField()),
                ('name', models.TextField()),
            ],
        ),
    ]
