# Generated by Django 4.1.6 on 2023-05-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_finder', '0015_profile_finder_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_finder',
            name='family_about_candidate',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='profile_finder',
            name='family_current_status',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='profile_finder',
            name='family_fatherbirthcity',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='profile_finder',
            name='family_fatherbirthcountry',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='profile_finder',
            name='family_fatherjob',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='profile_finder',
            name='family_fathername',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='profile_finder',
            name='family_motherbirthcity',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='profile_finder',
            name='family_motherbirthcountry',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='profile_finder',
            name='family_motherjob',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='profile_finder',
            name='family_mothername',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='profile_finder',
            name='family_sib1dob',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='profile_finder',
            name='family_sib1email',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='profile_finder',
            name='family_sib1martial',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='profile_finder',
            name='family_sib1name',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='profile_finder',
            name='family_sib1occupations',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='profile_finder',
            name='family_sib1relation',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='profile_finder',
            name='family_sib1young',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='profile_finder',
            name='family_sib2dob',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='profile_finder',
            name='family_sib2email',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='profile_finder',
            name='family_sib2martial',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='profile_finder',
            name='family_sib2name',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='profile_finder',
            name='family_sib2occupations',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='profile_finder',
            name='family_sib2relation',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='profile_finder',
            name='family_sib2young',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='profile_finder',
            name='family_status',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
