# Generated by Django 4.1.6 on 2023-05-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_finder', '0016_profile_finder_family_about_candidate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_finder',
            name='contact_city',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='profile_finder',
            name='contact_country',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='profile_finder',
            name='contact_facebookurl',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='profile_finder',
            name='contact_fatherhousename',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='profile_finder',
            name='contact_fathername',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='profile_finder',
            name='contact_instagramurl',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='profile_finder',
            name='contact_linkurl',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='profile_finder',
            name='contact_mailid',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='profile_finder',
            name='contact_motherhousename',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='profile_finder',
            name='contact_phonenum',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='profile_finder',
            name='contact_street',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='profile_finder',
            name='contact_twitterurl',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='profile_finder',
            name='contact_websiteurl',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='profile_finder',
            name='contact_whatsappnum',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='profile_finder',
            name='contact_youtubeurl',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='profile_finder',
            name='contact_zipcode',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
