# Generated by Django 4.1.6 on 2023-05-06 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_finder', '0018_profile_finder_course_profile_finder_course1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_finder',
            name='food_taste_option',
            field=models.TextField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
