# Generated by Django 4.1.6 on 2023-05-11 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_finder', '0019_profile_finder_food_taste_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_finder',
            name='name',
            field=models.TextField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
