# Generated by Django 4.1.6 on 2023-05-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_finder', '0020_profile_finder_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_finder',
            name='aadhar',
            field=models.TextField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile_finder',
            name='address',
            field=models.TextField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile_finder',
            name='district',
            field=models.TextField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile_finder',
            name='gender',
            field=models.TextField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile_finder',
            name='pincode',
            field=models.TextField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
