# Generated by Django 4.2.1 on 2023-05-13 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_finder', '0023_profile_finder_dobo_profile_finder_father_nameo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_finder',
            name='profileforwho',
            field=models.TextField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
