# Generated by Django 4.2.1 on 2023-05-15 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_finder', '0024_profile_finder_profileforwho'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_finder',
            name='religion',
            field=models.TextField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
