# Generated by Django 4.2.1 on 2023-05-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_finder', '0027_profile_finder_family_fatherfamilyname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_finder',
            name='company_name1',
            field=models.TextField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile_finder',
            name='position1',
            field=models.TextField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile_finder',
            name='salary_range1',
            field=models.TextField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
