# Generated by Django 4.2.1 on 2023-05-17 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_finder', '0028_profile_finder_company_name1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_finder',
            name='profile_visibility',
            field=models.TextField(blank=True, default='All members', max_length=500, null=True),
        ),
    ]
