# Generated by Django 4.2.1 on 2023-05-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_finder', '0029_profile_finder_profile_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_finder',
            name='profile_visibility',
            field=models.TextField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
