# Generated by Django 4.2.1 on 2023-05-23 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_finder', '0031_profile_finder_age_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='follow_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.IntegerField(blank=True, default=None, max_length=10, null=True)),
                ('receiver_id', models.IntegerField(blank=True, default=None, max_length=10, null=True)),
                ('accept', models.TextField(blank=True, default=None, max_length=10, null=True)),
                ('name', models.TextField(blank=True, default=None, max_length=10, null=True)),
                ('place', models.TextField(blank=True, default=None, max_length=10, null=True)),
            ],
        ),
    ]
