# Generated by Django 4.2.1 on 2023-05-24 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_finder', '0032_follow_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow_request',
            name='name',
            field=models.TextField(blank=True, default=None, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='follow_request',
            name='place',
            field=models.TextField(blank=True, default=None, max_length=10000, null=True),
        ),
    ]
