# Generated by Django 4.0 on 2023-06-06 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_finder', '0033_alter_follow_request_name_alter_follow_request_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=30)),
                ('date_of_marriage', models.CharField(max_length=30)),
                ('words_about_marrio', models.CharField(max_length=300)),
                ('marriage_photos', models.ImageField(upload_to='media/happycoupls')),
            ],
        ),
    ]
