# Generated by Django 4.0 on 2023-06-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_finder', '0034_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_finder',
            name='block_list',
            field=models.TextField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
