# Generated by Django 4.2.2 on 2023-06-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_finder', '0035_profile_finder_block_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow_request',
            name='receiver_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='follow_request',
            name='sender_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
