# Generated by Django 4.2.2 on 2023-06-28 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_finder', '0036_alter_follow_request_receiver_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='marriage_photos',
        ),
    ]
