# Generated by Django 4.2.2 on 2023-06-28 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_finder', '0037_remove_upload_marriage_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='marriage_photos',
            field=models.ImageField(null=True, upload_to='media/happycoupls'),
        ),
    ]
