# Generated by Django 4.2.2 on 2023-06-28 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_finder', '0038_upload_marriage_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='useremail',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
