# Generated by Django 4.2.2 on 2023-06-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_finder', '0041_alter_upload_marriage_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='date_of_marriage',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='upload',
            name='fullname',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='upload',
            name='words_about_marrio',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
