# Generated by Django 4.2.2 on 2023-06-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_finder', '0042_alter_upload_date_of_marriage_alter_upload_fullname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='marriage_photos',
            field=models.ImageField(default='', upload_to='media/happycoupls'),
        ),
    ]
